CREATE DATABASE IF NOT EXISTS LoopDb
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE LoopDb;


CREATE TABLE users (
  Id CHAR(36) NOT NULL PRIMARY KEY,
  Username VARCHAR(100) NOT NULL,
  Email VARCHAR(255) NOT NULL,
  HashedPassword VARCHAR(255) NOT NULL,
  CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT UQ_users_Username UNIQUE (Username)
);


CREATE TABLE posts (
  Id CHAR(36) NOT NULL PRIMARY KEY,
  AuthorId CHAR(36) NOT NULL,
  Content VARCHAR(1000) NOT NULL,
  CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY IX_posts_author (AuthorId),
  CONSTRAINT FK_posts_users FOREIGN KEY (AuthorId)
    REFERENCES users (Id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
); 


