CREATE DATABASE LoopDb
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE LoopDb;

CREATE TABLE users (
  Id VARCHAR(36) NOT NULL PRIMARY KEY,
  Username VARCHAR(100) NOT NULL UNIQUE,
  Email VARCHAR(255) NOT NULL UNIQUE,
  HashedPassword VARCHAR(255) NOT NULL,
  CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE posts (
  Id VARCHAR(36) NOT NULL PRIMARY KEY,
  AuthorId VARCHAR(36) NOT NULL,
  Content VARCHAR(1000) NOT NULL,
  CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (AuthorId) REFERENCES users(Id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
); 

